import type { Book } from './types'

// Geometry hand-tuned in a 440×360 space for an organic, drawn look.
// Lower branches are longer/older; higher branches shorter/younger.
export const daodejing: Book = {
  id: 'daodejing',
  title: '《道德经》',
  readerName: '沈一苇',
  plantedLabel: '种于 2023 年冬',
  branches: [
    {
      id: 'ch11',
      label: '十一',
      chapter: '第十一章',
      d: 'M 220 250 Q 276 234 332 231',
      w: 1.5,
      leaf: 'cinnabar',
      leafAt: { x: 332, y: 231 },
      labelAt: { x: 342, y: 235, anchor: 'start' },
      drawDelay: '0.9s',
      leafDelay: '1.7s',
      state: '入木',
      genre: '证',
      source: '当其无,有器之用。',
      note: '学陶那年最废的一只碗,是我捏得最厚的那只——几乎没有「无」,盛不下什么。',
      sign: '沈一苇 · 2023 冬',
      thread: { d: 'M 332 231 L 374 205', at: { x: 378, y: 201 }, label: '陈拾 · 3 年后接续' },
    },
    {
      id: 'ch8',
      label: '八',
      chapter: '第八章',
      d: 'M 220 214 Q 168 202 116 196',
      w: 1.4,
      leaf: '',
      labelAt: { x: 106, y: 200, anchor: 'end' },
      drawDelay: '1.15s',
      leafDelay: '1.7s',
      state: '读过',
      source: '上善若水。',
    },
    {
      id: 'ch44',
      label: '四十四',
      chapter: '第四十四章',
      d: 'M 221 176 Q 268 166 312 162',
      w: 1.3,
      leaf: 'verdigris',
      leafAt: { x: 312, y: 162 },
      labelAt: { x: 322, y: 166, anchor: 'start' },
      drawDelay: '1.4s',
      leafDelay: '2.0s',
      state: '青芽',
      genre: '证',
      source: '知足不辱,知止不殆。',
      note: '辞掉第二份工作的那晚我写:知道停在哪里,比知道去哪里难。',
      sign: '沈一苇 · 2025 春',
    },
    {
      id: 'ch22',
      label: '二十二',
      chapter: '第二十二章',
      d: 'M 220 146 Q 178 138 138 134',
      w: 1.2,
      leaf: '',
      labelAt: { x: 128, y: 138, anchor: 'end' },
      drawDelay: '1.65s',
      leafDelay: '2.2s',
      state: '读过',
      source: '曲则全,枉则直。',
    },
    {
      id: 'ch64',
      label: '六十四',
      chapter: '第六十四章',
      d: 'M 221 116 Q 256 108 288 105',
      w: 1.1,
      leaf: '',
      labelAt: { x: 298, y: 109, anchor: 'start' },
      drawDelay: '1.9s',
      leafDelay: '2.4s',
      state: '读过',
      source: '千里之行,始于足下。',
    },
  ],
  echo: {
    lead: '一年前的你,在「知足不辱,知止不殆」之下写过一枚青芽。',
    quote: '辞掉第二份工作的那晚我写:知道停在哪里,比知道去哪里难。',
    ask: '现在的你,还这么读吗?',
  },
  shelf: {
    shortTitle: '道德經',
    year: -400,
    width: '38px',
    height: '236px',
    fontSize: '16px',
    seal: true,
    line: '五千字,两千年读不尽。',
    meta: '已生长约 2,400 年 · 137 层年轮',
    live: true,
  },
}
