import type { Book } from './types'

// Same hand-drawn tree geometry as 道德经 (the tree's shape is a generic
// template — every reader's tree grows the same way; only the chapters,
// leaves and ink on it differ book to book).
export const xinjing: Book = {
  id: 'xinjing',
  title: '《心经》',
  readerName: '沈一苇',
  plantedLabel: '种于 2022 年夏',
  branches: [
    {
      id: 'seg-sekong',
      label: '色空',
      chapter: '「色即是空」句',
      d: 'M 220 250 Q 276 234 332 231',
      w: 1.5,
      leaf: 'cinnabar',
      leafAt: { x: 332, y: 231 },
      labelAt: { x: 342, y: 235, anchor: 'start' },
      drawDelay: '0.9s',
      leafDelay: '1.7s',
      state: '入木',
      genre: '证',
      source: '色不异空,空不异色,色即是空,空即是色。',
      note: '住院那年盯着天花板念这四句,忽然不怕了——不是想通,是想穿。',
      sign: '沈一苇 · 2022 夏',
      thread: { d: 'M 332 231 L 374 205', at: { x: 378, y: 201 }, label: '林知 · 2 年后接续' },
    },
    {
      id: 'seg-wuyun',
      label: '五蕴',
      chapter: '「照见五蕴皆空」句',
      d: 'M 220 214 Q 168 202 116 196',
      w: 1.4,
      leaf: '',
      labelAt: { x: 106, y: 200, anchor: 'end' },
      drawDelay: '1.15s',
      leafDelay: '1.7s',
      state: '读过',
      source: '观自在菩萨,行深般若波罗蜜多时,照见五蕴皆空,度一切苦厄。',
    },
    {
      id: 'seg-kongxiang',
      label: '空相',
      chapter: '「诸法空相」句',
      d: 'M 221 176 Q 268 166 312 162',
      w: 1.3,
      leaf: 'verdigris',
      leafAt: { x: 312, y: 162 },
      labelAt: { x: 322, y: 166, anchor: 'start' },
      drawDelay: '1.4s',
      leafDelay: '2.0s',
      state: '青芽',
      genre: '疑',
      source: '是诸法空相,不生不灭,不垢不净,不增不减。',
      note: '不垢不净好懂,不增不减总像是句安慰话——还没想透,先记下这枚疑。',
      sign: '沈一苇 · 2025 秋',
    },
    {
      id: 'seg-wugua',
      label: '无碍',
      chapter: '「心无挂碍」句',
      d: 'M 220 146 Q 178 138 138 134',
      w: 1.2,
      leaf: '',
      labelAt: { x: 128, y: 138, anchor: 'end' },
      drawDelay: '1.65s',
      leafDelay: '2.2s',
      state: '读过',
      source: '心无挂碍,无挂碍故,无有恐怖,远离颠倒梦想,究竟涅槃。',
    },
    {
      id: 'seg-jiedi',
      label: '揭谛',
      chapter: '「揭谛咒」句',
      d: 'M 221 116 Q 256 108 288 105',
      w: 1.1,
      leaf: '',
      labelAt: { x: 298, y: 109, anchor: 'start' },
      drawDelay: '1.9s',
      leafDelay: '2.4s',
      state: '读过',
      source: '揭谛揭谛,波罗揭谛,波罗僧揭谛,菩提萨婆诃。',
    },
  ],
  echo: {
    lead: '一年前的你,在「诸法空相」之下写过一枚青芽。',
    quote: '不垢不净好懂,不增不减总像是句安慰话——还没想透,先记下这枚疑。',
    ask: '现在的你,还这么疑着吗?',
  },
  shelf: {
    shortTitle: '心經',
    year: 649,
    width: '22px',
    height: '176px',
    fontSize: '14px',
    seal: true,
    line: '二百六十字,照见五蕴皆空。',
    meta: '已生长约 1,380 年 · 62 层年轮',
    live: true,
  },
}
